### ISSUE TITLE
Few minor bugs and suggestions

### ISSUE THREAD

**Issue by hp2048** [Sydney-Informatics-Hub/Gadi-Trinity#6]
Hi,
I have noticed some bugs and minor suggestions that you may want to incorporate.

1. A typo in the patch file. 
https://github.com/Sydney-Informatics-Hub/Gadi-Trinity/blob/81d0791d5956c927571ab3e55d5bb510041b91d1/resources/Trinity-2.12.0.patch#L32

2. Adding the use of following two modules in the `Trinity` in the patch file as well.

```
use File::Path qw(make_path remove_tree);
use POSIX ();
```

Also, the path to version of the trinity is hardcoded in the output file. Perhaps it can be set as a parameter `trinity_version` in job scripts to facilitate appropriate version upgrades.

3. Trinity run with version 2.9.1 gives following error. I haven't debugged that. Perhaps you may want to look into it.

```
----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

Converting input files. (in parallel)Wednesday, August 25, 2021: 10:30:38	CMD: gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_1.fastq.gz | seqtk-trinity seq -A -R 1 - >> left.fa
Wednesday, August 25, 2021: 10:30:38	CMD: gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_2.fastq.gz | seqtk-trinity seq -A -R 2 - >> right.fa
bash: line 1: 358048 Broken pipe             gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_1.fastq.gz
     358049 Segmentation fault      | seqtk-trinity seq -A -R 1 - >> left.fa
Thread 1 terminated abnormally: Error, cmd: gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_1.fastq.gz | seqtk-trinity seq -A -R 1 - >> left.fa died with ret 35584 at /tmp//apps/trinity/2.9.1/Trinity line 2802 thread 1.
	main::process_cmd("gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitti"...) called at /tmp//apps/trinity/2.9.1/Trinity line 2689 thread 1
	eval {...} called at /tmp//apps/trinity/2.9.1/Trinity line 2646 thread 1
	main::prep_seqs(ARRAY(0x5629ba423210), "fq", "left", undef) called at /tmp//apps/trinity/2.9.1/Trinity line 1532 thread 1
	eval {...} called at /tmp//apps/trinity/2.9.1/Trinity line 1532 thread 1
bash: line 1: 358052 Broken pipe             gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_2.fastq.gz
     358053 Segmentation fault      | seqtk-trinity seq -A -R 2 - >> right.fa
Thread 2 terminated abnormally: Error, cmd: gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitticeps/rnaseq/DRR034338_2.fastq.gz | seqtk-trinity seq -A -R 2 - >> right.fa died with ret 35584 at /tmp//apps/trinity/2.9.1/Trinity line 2802 thread 2.
	main::process_cmd("gunzip -c /g/data/xl04/publicdata/ncbitxid103695_pogona.vitti"...) called at /tmp//apps/trinity/2.9.1/Trinity line 2689 thread 2
	eval {...} called at /tmp//apps/trinity/2.9.1/Trinity line 2646 thread 2
	main::prep_seqs(ARRAY(0x5629ba51acd0), "fq", "right", undef) called at /tmp//apps/trinity/2.9.1/Trinity line 1535 thread 2
	eval {...} called at /tmp//apps/trinity/2.9.1/Trinity line 1535 thread 2
Error prepping sequences. at /tmp//apps/trinity/2.9.1/Trinity line 1543.

Trinity run failed. Must investigate error above.
Wed Aug 25 10:30:38 AEST 2021 : Finished trinity_1.pbs
Wed Aug 25 10:30:38 AEST 2021 : Archiving trinity outdir and copying to /g/data/xl04/hrp561/pogonatranscriptome/analysis/Trinity/DRR034338
Wed Aug 25 10:30:38 AEST 2021 : Finished archiving trinity_1.pbs
Final assembly will commence after jobs: 
```

4. Perhaps consider adding `set -ex` in bash scripts to make them robust.
5. `qsub` command needs update to include gdata storage as well: `-l storage=scratch/${project}+gdata/${project}`
6. There are no check-points in the workflow. If the run fails halfway through, it starts all over again. Perhaps this can be introduced to avoid resubmitting the same jobs again by mistake and also to reduce the compute time required if the steps have already finished successfully.

I am running a test now with some of these updates. Will update once I have results.

**Comment by hp2048** [comment]
I have managed to run up to stage 2 of the assembly using the changes I specified above. It failed at stage3. I have given up for now in favour of just running the Trinity command straight up on a single node with 48 cores. This has successfully run 251 samples (see details at https://github.com/kango2/pogo). Since it is not onerous to run Trinity on a single node and it is efficient, I will stick with my plan and unfortunately won't test this further. I leave it up to you to close the issue.

**Comment by georgiesamaha** [comment]
Hi @hp2048,

Thanks for the suggestions. We're currently working on resolving your issues and will get back to you shortly. Regarding your inability to run stage 3, could you please share the relevant errors in the job_3.o and job_3.e files with us?

**Comment by hp2048** [comment]
Hi @georgiesamaha : I have removed the directory completely. I will rerun it and send you the results.
Cheers
Hardip

**Comment by georgiesamaha** [comment]
Closing this issue, feel free to reopen.
