### ISSUE TITLE
parallelisation

### ISSUE THREAD

**Issue by hp2048** [Sydney-Informatics-Hub/Gadi-Trinity#7]
Hi
I was wondering how parallelisation is achieved using these scripts. I have launched the job and it seems to be running only on a single node. How is this different from Trinity's `parafly` option where commands are run in parallel when possible using the `parafly` utility.
Cheers

**Comment by georgiesamaha** [comment]
Sorry for the delay, thanks for the question :)  

Parallelism is achieved in a few ways with this workflow. 

First, the workflow submits each sample listed in the fastq.list as a separate, single node job. Parallelism here is achieved by running multiple samples concurrently.

Second, for job_2, a single node job is submitted for each of the file bin (fb) directories that are created. The number of fbs created depends on the size of your data so this stage scales naturally with the size of the task. Each of these directories contains 100 K small tasks. 

Finally, we have used ParaFfly to run each of these 100 K tasks in job_2_fb in parallel. We did a lot of benchmarking to make sure we chose the optimal configuration. We compared ParaFly and nci-parallel for this and ParaFly consistently outperformed nci-parallel in terms of efficiency. 

Together all these optimisations have been enabled Trinity to use multiple nodes in the most efficient way on Gadi (considering SU consumption).

Does that clarify things?
